### ISSUE TITLE
Module compiled with Swift 4.1.2 cannot be imported by the Swift 4.2.1 compiler

### ISSUE THREAD

**Issue by Shiva2005** [zoho/ZohoDeskPortalSDK#1]
While importing, i am getting like this.

**Comment by Larry-Zoho** [comment]
@Shiva2005 . 

I'd recommend checking this [https://www.zoho.com/desk/developers/asap/mobile-sdk/ios/](url) for more details. We are available on "support[at]zohodesk[dot]com"

**Comment by Shiva2005** [comment]
Hi,
After integrating this code only, I got this error.

Thanks & Regards,
Siva Shankar

**Comment by Larry-Zoho** [comment]
Hi,
Sorry about that, it looks like our help document had an outdated Xcode file (ver 9.3). We are updating the document right now with the updated version. 

In the meantime, please get the latest version from the below URL. 

[https://github.com/zoho/ZohoDeskPortalSDK/archive/Xcode_10.0.zip](url)

**Comment by DevangTandel** [comment]
> Hi,
> Sorry about that, it looks like our help document had an outdated Xcode file (ver 9.3). We are updating the document right now with the updated version.
> 
> In the meantime, please get the latest version from the below URL.
> 
> [https://github.com/zoho/ZohoDeskPortalSDK/archive/Xcode_10.0.zip](url)

This is not working.

**Comment by Larry-Zoho** [comment]
Hi DevangTandel,

We will be able to help you with this. Would you be willing to share your contact details to "support(at)zohodesk(dot)com". We shall take this forward.
