### ISSUE TITLE
Compilation Error with XCode 12.5

### ISSUE THREAD

**Issue by rajasekar259** [zoho/ZohoDeskPortalSDK#10]
Compilation Error with XCode 12.5: Module compiled with Swift 5.3.1 cannot be imported by the Swift 5.4 compiler.
![image](https://user-images.githubusercontent.com/11645496/116422141-11dc3080-a85d-11eb-9747-45f0c771e1e9.png)

**Comment by balasubramanian-k-19828** [comment]
We have support for Xcode 12.5 in live and would suggest integrating ZohoDeskPortalSDK via below pod:

pod 'ZohoDeskPortalSDK', :git => 'https://github.com/zoho/ZohoDeskPortalSDK.git', :tag => '1.1.15_12.5'

In the meantime, kindly migrate to our 2.x version where

- We have provided our SDK as XCFramework so as to rectify the Swift versioning issue.
- Also, we have adopted more new features. For more informations, refer to the links shared below.

[2.x DOC](https://help.zoho.com/portal/en/kb/desk/for-developers/asap/ios-sdk/articles/working-with-asap-sdk-for-ios#SDK_v20) 

[Migration from 1.x to 2.x](https://help.zoho.com/portal/en/kb/desk/for-developers/asap/ios-sdk/articles/working-with-asap-sdk-for-ios#Migrating_from_v1x_to_v20)

Should you have any queries, feel free to hit us up at support@zohodesk.com, @rajasekar259
