### ISSUE TITLE
Support more Localization Key in ZohoDeskPortalSDK

### ISSUE THREAD

**Issue by hieplam** [zoho/ZohoDeskPortalSDK#11]
according to [this link](https://help.zoho.com/portal/en/kb/desk/for-developers/asap/ios-sdk/articles/working-with-asap-sdk-for-ios#Changing_Language_Settings) there are about 25 keys that support multi-language. 

Are there any way to custom more? especially in live chat feature, i need to fully customize language (in chat feature) in Vietnamese.

Or is there anyplace that i can custom in the sourcecode.

Thanks

**Comment by balasubramanian-k-19828** [comment]
Hi @hieplam 

We don't have support for chat module Strings. This is in road map. Once we implemented this will intimate you. 

Do you have any queries or need further support, feel free to hit us up at support@zohodesk.com.

Thanks.

**Comment by hieplam** [comment]
so chat Strings haven't supported yet. there is one more issue on for the link above.
![image](https://user-images.githubusercontent.com/10095360/126744885-301e932f-9a9d-46ec-93ae-1bf295263ab2.png)

the link to download 34 languages is not working, please update the link for me

**Comment by balram1990** [comment]
Hi @Bala-Karunakaran, as mentioned by @hieplam, the link is not woking(highlighted one). Can you please share the actual link to download the bundles for one of the other 34 language supported?

Thanks.

**Comment by balasubramanian-k-19828** [comment]
Kindly check with our latest version. [Help Document](https://help.zoho.com/portal/en/kb/desk/for-developers/asap/ios-sdk/articles/working-with-asap-sdk-for-ios#SDK_v20)
