### ISSUE TITLE
Please support Xcode 13.3

### ISSUE THREAD

**Issue by nhunguyen-piktina** [zoho/ZohoDeskPortalSDK#12]
Hi team,

I got an error `Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.6 compiler:` whie running this project by xcode 13.3.

**Comment by balasubramanian-k-19828** [comment]
Hi @nhunguyen-piktina 

We have deprecated the 1.x versions SDK and have given ABI stability support from 2.0 version. We would suggest migrating to the 2.x version.

Here's the 2.x document: https://help.zoho.com/portal/en/kb/desk/for-developers/asap/ios-sdk/articles/working-with-asap-sdk-for-ios

Here's the 1.x to 2.x migration document: https://help.zoho.com/portal/en/kb/desk/for-developers/asap/ios-sdk/articles/working-with-asap-sdk-for-ios#Integrating_the_SDK_with_Your_iOS_App

 I'd suggest reaching out to us at support@zohodesk.com for further scrutiny
