### ISSUE TITLE
Arm64 Apple silicon support

### ISSUE THREAD

**Issue by timonchev** [zoho/ZohoDeskPortalSDK#13]
Hello, can you fix your frameworks for correct Apple silicon M1 simulator support natively? 
mom this moment I see that arm64 need be excluded for sdks work. 
Thank you

**Comment by balasubramanian-k-19828** [comment]
Hi @timonchev 
We have deprecated the 1.x versions SDK and have given ABI stability support from 2.0 version. We would suggest migrating to the 2.x version.

Here's the 2.x document: https://help.zoho.com/portal/en/kb/desk/for-developers/asap/ios-sdk/articles/working-with-asap-sdk-for-ios

Here's the 1.x to 2.x migration document: https://help.zoho.com/portal/en/kb/desk/for-developers/asap/ios-sdk/articles/working-with-asap-sdk-for-ios#Integrating_the_SDK_with_Your_iOS_App

I'd suggest reaching out to us at [support@zohodesk.com](mailto:support@zohodesk.com) for further scrutiny
