### ISSUE TITLE
ZohoDesk v2.2 is not supported with new Xcode14

### ISSUE THREAD

**Issue by anweshannu** [zoho/ZohoDeskPortalSDK#14]
Hi, Im trying to integrate zohodesk ios sdk in My app it. It is throwing the below error.  Please provide me the new SDK built with xcode14 (swift v5.7.1)

failed to build module 'ZohoDeskPortalServices'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.5 (swiftlang-1300.0.31.1 clang-1300.0.29.1)', while this compiler is 'Apple Swift version 5.7.1 (swiftlang-5.7.1.135.3 clang-1400.0.29.51)'). Please select a toolchain which matches the SDK.

**Comment by balasubramanian-k-19828** [comment]
Hi @anweshannu ,

We debug this case in Xcode 14.0 and Xcode 14.2 with our 'ZohoDeskPortalServices' 2.2 version. Its working fine for us.

Still you face the issue, I'd suggest reaching out to us at [support@zohodesk.com](mailto:support@zohodesk.com) with maximum information.

Thanks.
