### ISSUE TITLE
Error on ZohoDeskPortalCore import

### ISSUE THREAD

**Issue by MarcioDcv** [zoho/ZohoDeskPortalSDK#15]
Hello guys

**Error**:
Failed to build module 'ZohoDeskPortalCore'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.7.1 (swiftlang-5.7.1.135.3 clang-1400.0.29.51)', while this compiler is 'Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)'). Please select a toolchain which matches the SDK.

**My pod install:** 

Installing SwiftProtobuf (1.19.0)
Installing ZDChat (2.3.5)
Installing ZDMediaPickerSDK (1.0.5)
Installing ZohoDeskPlatformDataBridge (1.0.11)
Installing ZohoDeskPlatformUIKit (1.0.11)
Installing ZohoDeskPortalAPIKit (3.0.1)
Installing ZohoDeskPortalCommunity (3.0.1)
Installing ZohoDeskPortalConfiguration (3.0.1)
Installing ZohoDeskPortalCore (3.0.1)
Installing ZohoDeskPortalKB (3.0.1)
Installing ZohoDeskPortalLiveChat (3.0.1)
Installing ZohoDeskPortalTicket (3.0.1)
Installing ZohoPubSubSDK (1.2.5)

Thanks

**Comment by balasubramanian-k-19828** [comment]
Hi @MarcioDcv 

It appears you are currently utilizing version 3.0.1. The compiler issue has been resolved in our most recent release, version 3.0.2. Please verify with the updated version.

If the problem persists, we recommend contacting us at [support@zohodesk.com](mailto:support@zohodesk.com) and providing comprehensive information for further assistance.

Thank you.
