### ISSUE TITLE
Issue with XCode 10 and Swift 4.2.1

### ISSUE THREAD

**Issue by aramobile** [zoho/ZohoDeskPortalSDK#2]
Hi there,
After integrating manually framework SDK branch XCode_10.0 for Xcode 10, there's an error when building the app. No symbol found for architecture arm64.
Any help please ?

**Comment by balasubramanian-k-19828** [comment]
We have deprecated the 1.x versions SDK and have given ABI stability support from 2.0 version. We would suggest migrating to the 2.x version.

Here's the 2.x document: https://help.zoho.com/portal/en/kb/desk/for-developers/asap/ios-sdk/articles/working-with-asap-sdk-for-ios

Here's the 1.x to 2.x migration document: https://help.zoho.com/portal/en/kb/desk/for-developers/asap/ios-sdk/articles/working-with-asap-sdk-for-ios#Integrating_the_SDK_with_Your_iOS_App

I'd suggest reaching out to us at [support@zohodesk.com](mailto:support@zohodesk.com) for further scrutiny
