### ISSUE TITLE
Issue with xcode 11 and Swift 5.1

### ISSUE THREAD

**Issue by saurabh-silicon** [zoho/ZohoDeskPortalSDK#3]
With xcode 11, It gives compile time error.
Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 
![Screenshot 2019-10-03 at 4 00 19 PM](https://user-images.githubusercontent.com/29114655/66121259-688a7580-e5fa-11e9-8ad1-e8135d794399.png)

**Comment by Larry-Zoho** [comment]
@saurabh-silicon , 

Sorry about the delayed update. 

Support for Xcode 11 and Xcode 11.2 has been updated. 

Please use the below pod for Xcode 11 & 11.1

'ZohoDeskPortalSDK', :git => 'https://github.com/zoho/ZohoDeskPortalSDK.git', :tag => 'Xcode_11'`

For Xcode 11.2 & 11.2.1

'ZohoDeskPortalSDK', :git => 'https://github.com/zoho/ZohoDeskPortalSDK.git', :tag => 'Xcode_11.2'
