### ISSUE TITLE
Deprecated API Usage of UIWebView

### ISSUE THREAD

**Issue by timonchev** [zoho/ZohoDeskPortalSDK#4]
Hello, can you check please that ZahoDeskPortalSDK used only WKWebView.

With your SDK I get issue from Apple:

Dear Developer,

We identified one or more issues with a recent delivery for your app,  Your delivery was successful, but you may wish to correct the following issues in your next delivery:

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs starting from April 2020 . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

After you’ve corrected the issues, you can upload a new binary to App Store Connect.

Best regards,

The App Store Team

**Comment by Larry-Zoho** [comment]
Thank you for notifying, @timonchev . We've identified this issue and working on a fix right now. It will be updated on our upcoming build. 

We'll keep you posted. 

Thanks,
Zoho Desk.

**Comment by balasubramanian-k-19828** [comment]
Kindly check with our latest version. [Help Document](https://help.zoho.com/portal/en/kb/desk/for-developers/asap/ios-sdk/articles/working-with-asap-sdk-for-ios#SDK_v20)
