### ISSUE TITLE
ABI Stability

### ISSUE THREAD

**Issue by jaol-gu** [zoho/ZohoDeskPortalSDK#5]
Hello,

Swift since 5.1 supports module stability. However, there are still problems when importing `ZohoDeskPortalSDK` like `Module compiled with Swift 5.2 cannot be imported by the Swift 5.1.3`.

It leads to a lot of compatibility issues especially when using CI etc.

Could you make sure that `Build Libraries for Distribution` is enabled for your library?

Please refer to this WWDC session for more information: https://developer.apple.com/videos/play/wwdc2019/416/

**Comment by Larry-Zoho** [comment]
@jaol-gu , Thank you for posting your concern. 

We understand the compatibility issues and module stability. Our team has been working on this in parallel  to the current updates. At the moment, we do not have a definitive ETA as to when this new implementation will be released, but 2-3 weeks can be taken as an approximation. 

Additionally, the following can be used as a workaround for the respect Xcode versions. 

For Xcode 11.3
`pod 'ZohoDeskPortalSDK', :git => 'https://github.com/zoho/ZohoDeskPortalSDK.git', :tag => '1.1.11_11.3'
`
For Xcode 11.4
`pod 'ZohoDeskPortalSDK', :git => 'https://github.com/zoho/ZohoDeskPortalSDK.git', :tag => '1.1.11_11.4'`

**Comment by balasubramanian-k-19828** [comment]
Kindly check with our latest version. [Help Document](https://help.zoho.com/portal/en/kb/desk/for-developers/asap/ios-sdk/articles/working-with-asap-sdk-for-ios#SDK_v20)
