### ISSUE TITLE
Same SDK version not worked with XCode 11.6 & XCode 12

### ISSUE THREAD

**Issue by iamitmishra** [zoho/ZohoDeskPortalSDK#7]
Let me know if you have any SDK version which will work in both Xcode 11.6 & Xcode 12.

I have tried below but not get success in both.
pod 'ZohoDeskPortalSDK', :git => 'https://github.com/zoho/ZohoDeskPortalSDK.git', :tag => '1.1.12_11.4'
pod 'ZohoDeskPortalSDK', :git => 'https://github.com/zoho/ZohoDeskPortalSDK.git', :tag => '1.1.11_11.4'
pod 'ZohoDeskPortalSDK', :git => 'https://github.com/zoho/ZohoDeskPortalSDK.git', :tag => '1.1.13_12.0'

Not found any which works in both versions of XCode.

**Comment by Larry-Zoho** [comment]
@iamitmishra ,

Apparently,  1.x versions of ZohoDeskPortalSDK  are fat frameworks; Hence it won’t support ABI stability.However, from versions 2.0 we've added support to  XCFramework and it will support ABI stability.

Please check this [document](https://help.zoho.com/portal/en/kb/desk/for-developers/asap/ios-sdk/articles/working-with-asap-sdk-for-ios) for more details.

**Comment by iamitmishra** [comment]
I have also tried to follow the document version 2.0 but it gives me error in Xcode 11.6 

I have removed derive data but still it gives this error.

![Screenshot 2020-10-31 at 10 58 06 AM](https://user-images.githubusercontent.com/60083250/97771945-09ce5d00-1b68-11eb-9c39-1c9449245de6.png)

**Comment by balasubramanian-k-19828** [comment]
Kindly check with our latest version. [Help Document](https://help.zoho.com/portal/en/kb/desk/for-developers/asap/ios-sdk/articles/working-with-asap-sdk-for-ios#SDK_v20)
