### ISSUE TITLE
Alignment issue 

### ISSUE THREAD

**Issue by anshuvij** [zoho/ZohoDeskPortalSDK#9]
alignment issue occurs after app is removed from background and relaunched.
Please let me know the solution as apple rejected our app because of this.

![IMG_950B770B218F-1](https://user-images.githubusercontent.com/12726615/115755253-c89e6380-a3ba-11eb-9da8-9659454d8b92.jpeg)

**Comment by anshuvij** [comment]
![IMG_950B770B218F-1](https://user-images.githubusercontent.com/12726615/115755611-2763dd00-a3bb-11eb-98bb-730a3d67aad4.jpeg)

**Comment by balasubramanian-k-19828** [comment]
Hi @anshuvij ,

Can you please help us with some more information to debug the issue,

1. The podFile syntax which you used to integrate our SDK.
2. Your's Xcode version.

**Comment by anshuvij** [comment]
I am using  pod 'ZohoDeskPortalCore' for podFile. 
The issue occurs on both Xcode 11 and 12 both.
And also when using navigationMode: .present for ZDHomePortal there is no option to go back to previous view controller

**Comment by balasubramanian-k-19828** [comment]
@anshuvij, Please draft the issues with maximum information and share the details to "support@zohodesk.com". We shall take this forward.

Thanks.

**Comment by anshuvij** [comment]
Hi, I have mailed with all the information. Looking forward for the fix
